// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"github.com/paulinethornberg/label-artist-fetcher/model"
	mock "github.com/stretchr/testify/mock"
)

// Builder is an autogenerated mock type for the Repository type
type Builder struct {
	mock.Mock
}

// LabelArtistCollection provides a mock function
func (_m *Builder) LabelArtistCollection(songCollection model.SongCollection) []model.Label {
	ret := _m.Called(songCollection)

	var r0 []model.Label
	if rf, ok := ret.Get(0).(func(model.SongCollection) []model.Label); ok {
		r0 = rf(songCollection)
	} else {
		r0 = ret.Get(0).([]model.Label)
	}

	return r0
}
