// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	"time"

	"github.com/paulinethornberg/label-artist-fetcher/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetPlaylistByChannel provides a mock function with given fields
func (_m *Repository) GetPlaylistByChannel(channel model.ChannelID, fromTime, toTime time.Time) (*model.SongCollection, error) {
	ret := _m.Called(channel, fromTime, toTime)

	var r0 *model.SongCollection
	if rf, ok := ret.Get(0).(func(model.ChannelID, time.Time, time.Time) *model.SongCollection); ok {
		r0 = rf(channel, fromTime, toTime)
	} else {
		r0 = ret.Get(0).(*model.SongCollection)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.ChannelID, time.Time, time.Time) error); ok {
		r1 = rf(channel, fromTime, toTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
